connections:
  DB2_CORE_BANKING:
    database: ''
    host: localhost
    port: ''
    type: UNKNOWN
  HDFS_FINANCE:
    database: ''
    host: localhost
    port: ''
    type: UNKNOWN
  HIVE_FINANCE_DW:
    database: ''
    host: localhost
    port: ''
    type: UNKNOWN
  ORACLE_CRM:
    database: ''
    host: localhost
    port: ''
    type: UNKNOWN
log_level: INFO
parameters:
  BATCH_SIZE: 100000
  COMPLIANCE_REGION: US
  ENV: PRODUCTION
  ERROR_THRESHOLD: 1
  LOAD_DATE: $$SystemDate
  LOAD_MONTH: $$SystemDate
  PARALLEL_DEGREE: 8
  RETENTION_DAYS: 2555
  RISK_THRESHOLD_HIGH: 50000
  RISK_THRESHOLD_MEDIUM: 10000
spark:
  spark.app.name: FinancialDW_Project
  spark.master: local[*]
  spark.sql.adaptive.coalescePartitions.enabled: 'true'
  spark.sql.adaptive.enabled: 'true'
  spark.sql.warehouse.dir: ./spark-warehouse
