connections:
  HDFS_RETAIL:
    database: ''
    host: localhost
    port: ''
    type: UNKNOWN
  HIVE_DW:
    database: ''
    host: localhost
    port: ''
    type: UNKNOWN
log_level: INFO
parameters:
  BATCH_SIZE: '10000'
  ENV: PROD
  ERROR_THRESHOLD: '5'
  LOAD_DATE: $$SystemDate
spark:
  spark.app.name: RetailETL_Project
  spark.master: local[*]
  spark.sql.adaptive.coalescePartitions.enabled: 'true'
  spark.sql.adaptive.enabled: 'true'
  spark.sql.warehouse.dir: ./spark-warehouse
