version: '3.8'

services:
  enterprise_complete_transformations:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - SPARK_MASTER=local[*]
