connections: {}
log_level: INFO
parameters: {}
spark:
  spark.app.name: Comprehensive_Transform_Test
  spark.master: local[*]
  spark.sql.adaptive.coalescePartitions.enabled: 'true'
  spark.sql.adaptive.enabled: 'true'
  spark.sql.warehouse.dir: ./spark-warehouse
